### ISSUE TITLE
About detected object proposals on ScanRefer setting

### ISSUE THREAD

**Issue by CurryYuan** [cshizhe/vil3dref#1]
Hi @cshizhe ,

Thanks for your excellent work. Will you release the model at the setting of detected object proposals on ScanRefer?

Best

**Comment by cshizhe** [comment]
Hi, I uploaded the [trained model](https://www.dropbox.com/sh/cqpo03591ox7yih/AACQIKsi05sJ4P_dKXrP0r4ha?dl=0) using detected object proposals from PointGroup on ScanRefer, which achieves acc@iou0.25 0.479, acc@iou0.5 0.377.
To be noted, the model using the groundtruth object proposals in training (in the original dropbox link in README) also achieves good generalization performance on detected object proposals with acc@iou0.25 0.466, acc@iou0.5 0.372.

**Comment by CurryYuan** [comment]
Hi @cshizhe ,

Thanks for sharing the trained model. I noticed that you provided the gt proposals. Could you also provide the detected proposals or share the processing code?

Best

**Comment by cshizhe** [comment]
You should first follow [PointGroup](https://github.com/dvlab-research/PointGroup) to generate the segmentation results and then process the data into a similar format as the gt proposals. Some preprocessing codes are released [here](https://github.com/cshizhe/vil3dref/tree/main/preprocess).
