### ISSUE TITLE
About the data preparation. 

### ISSUE THREAD

**Issue by timzsu** [cshizhe/vil3dref#2]
Thank you for the great work and the code! 

I noticed that you provided a compressed file of preprocessed files. Though it enables me to launch the whole pipeline, I was confused when I tried to modify the annotation file, since the encoded tokens are provided without instructions. Can you give some details about how the data are prepared? Or are they generated with ReferIt3D's token generation scripts? 

Thank you so much for your attention and participation in advance.

**Comment by cshizhe** [comment]
Hi, I uploaded the [preprocessing codes](https://github.com/cshizhe/vil3dref/tree/main/preprocess) to generate the annotation files. We use bert tokenizer in [huggingface transformers](https://github.com/huggingface/transformers) to get the encoded tokens.
