### ISSUE TITLE
Issues about trn_scan_split, val_scan_split and tst_scan_split

### ISSUE THREAD

**Issue by Yachao-Zhang** [cshizhe/vil3dref#4]
It seems that the splits (training，val., and test) are not  available. How can I get these files?

Regards!

**Comment by cshizhe** [comment]
It is in the referit3d/annotations/splits directory in the preprocessed data.

**Comment by Yachao-Zhang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            Hi cshizhe,Thanks Reply!In other words, I have to download the  preprocessed data to get them.  Get it.
    
        Kind regards,
            
        
    
    
     
    
        
            Yachao ***@***.***

        
    
 

    On 12/6/2022 21:15，Shizhe ***@***.***> wrote： 



It is in the referit3d/annotations/splits directory in the preprocessed data.
