### ISSUE TITLE
About the Evaluation Metrics of acc@0.25 and acc@0.5

### ISSUE THREAD

**Issue by Yachao-Zhang** [cshizhe/vil3dref#7]
Goog job and respect!
A qustion: For the Evaluation Metrics of acc@0.25 and acc@0.5, the model is trained on  the proposals provided by  GT or VoteNet/PointGroup?
Is it trained on GT and evaluated on VoteNet/PointGroup proposals? 
Thanks a lot!

**Comment by cshizhe** [comment]
Hi, we used the automatically generated proposals from [PointGroup](https://github.com/dvlab-research/PointGroup) in training and evaluation. We found the model trained on GT proposals performs slightly worse when evaluated on PointGroup proposals.
